name: drop_dylib_recording
description: Generate two dylibs, remove one in linking based on recorded usage.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.1.1
  meta: ^1.12.0
  # native_assets_cli: ^0.7.3
  native_assets_cli:
    path: ../../../native_assets_cli/
  # native_toolchain_c: ^0.5.3
  native_toolchain_c:
    path: ../../../native_toolchain_c/
  record_use: ^0.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0



dependency_overrides:
  meta:
    path: ../../../../../../dart-sdk/sdk/pkg/meta/
  record_use:
    path: ../../../../../../dart-sdk/sdk/pkg/record_use/