name: Health
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@forceFlutter
    with:
      coverage_web: false
      flutter_packages: pkgs/ffigen/**,pkgs/jni/**,pkgs/jnigen/**,pkgs/objective_c/**
      ignore_packages: pkgs/swiftgen/**,
      sdk: dev
      channel: master
    permissions:
      pull-requests: write
