name: Health
on:
  pull_request:
    branches: [ main ]
    # Remove paths after https://github.com/bmw-tech/dart_apitool/issues/177 is addressed.
    paths:
      - "pkgs/ffi/**"
      - "pkgs/native_assets_builder/**"
      - "pkgs/native_assets_cli/**"
      - "pkgs/native_toolchain_c/**"
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@forceFlutter
    with:
      coverage_web: false
      flutter_packages: "pkgs/ffigen/**,pkgs/jni/**,pkgs/jnigen/**,pkgs/objective_c/**"
      sdk: dev
      channel: master
    permissions:
      pull-requests: write
