# This workflow applies labels to pull requests based on the paths that are
# modified in the pull request.
#
# Edit `.github/labeler.yml` to configure labels. For more information, see
# https://github.com/actions/labeler.

name: Pull Request Labeler
permissions: read-all

on:
  pull_request_target

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        id: labelstep
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      
      - name: Fail if no label was added
        if: steps.labelstep.outputs.new-labels == '[]' && !contains(steps.labelstep.outputs.all-labels, 'skip-labeling-check')
        run: exit 1
